name: Update Release Badge

on:
  # release:
  #   types: [published]
  #   branches: [main]
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # - name: Install jq
    #   run: sudo apt-get install -y jq

    - name: Get latest release version
      id: get_release
      run: |
        latest_release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
        echo "::set-output name=version::$latest_release"

    - name: Update README with badge
      run: |
        badge_url="https://badgen.net/badge/release/${{ steps.get_release.outputs.version }}/blue"
        license_badge_url="https://img.shields.io/badge/license-MIT-red"
        badge_line="![Latest Release]($badge_url) ![License]($license_badge_url)"
        readme_file="readme.md"
        if grep -q '!\[Latest Release\]' "$readme_file"; then
          sed -i -E "s@!\[Latest Release\]\(.*\)@${badge_line}@" "$readme_file"
        else
          sed -i "1s|^|${badge_line}\n\n|" "$readme_file"
        fi

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add readme.md
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update release badge to version ${{ steps.get_release.outputs.version }}"
          git push origin HEAD:main
        fi
