name: aind_mcorr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - tifffile
  - h5py
  - matplotlib
  - pip
  - pip:
      - caiman @ git+https://github.com/flatironinstitute/CaImAn.git@v1.12.2
      - mesmerize-core>=0.5.0
      - opencv-python-headless
      - aind-data-schema
