FROM python:3.11-slim-bullseye

# Install system packages
RUN apt update && \
    apt install -y --no-install-recommends \
    gcc \
    g++ \
    libgl1 \
    mesa-vulkan-drivers \
    libgl1-mesa-glx \
    libegl1-mesa \
    libgl1-mesa-dev \
    libarchive13 \
    x11-apps \
    curl \
    git \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 
WORKDIR /home
RUN mkdir -p code
WORKDIR /home/code
COPY packages/uv_setup.sh /home/code/uv_setup.sh
RUN chmod +x /home/code/uv_setup.sh

# Install caiman environment
# WORKDIR $HOME
RUN /bin/bash /home/code/uv_setup.sh

# copy fix-permissions script from jupyter/base-notebook
COPY --from=jupyter/base-notebook /usr/local/bin/fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions

# Clean up
RUN rm -rf /home/code/uv_setup.sh

# Activate mescore environment by default
ENV PATH="/home/code/mescore/bin:$PATH"
RUN echo "source /root/.local/bin/env" >> /root/.profile
RUN echo "source /home/code/mescore/bin/activate" >> /root/.profile
SHELL [ "/bin/bash", "--login", "-c" ]
RUN echo "source /root/.local/bin/env" >> ~/.bashrc
RUN echo "source /home/code/mescore/bin/activate" >> ~/.bashrc
