# Builds and pushes docker and singularity images. 

# To update the `yml` file without triggering the job, use the `[skip ci]` or `[ci skip]` keyword in your commit message. 
# e.g.:
# ```
# Update docker-singularity-build.yml [skip ci]
# ```

name: Build and Push Docker and Singularity

on:
  release:
    types: [published]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # - name: Clear Docker cache
      #   run: |
      #     docker system prune -af
      #     docker builder prune -af
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker
        run: |
          docker --version
          docker buildx version

      - name: Build Docker image
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          # elif [[ $GITHUB_REF == refs/heads/* ]]; then
          #   TAG=${GITHUB_REF#refs/heads/}
          else
            TAG=latest
          fi
          mkdir -p containers/analysis_2p/context/Mesmerize
          rsync -avzP Mesmerize/ containers/analysis_2p/context/Mesmerize/
          docker build -t wanglabneuro/analysis-2p:latest -t wanglabneuro/analysis-2p:$TAG -f containers/analysis_2p/Dockerfile containers/analysis_2p/context --no-cache
          rm -rf containers/analysis_2p/context/Mesmerize

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push --all-tags wanglabneuro/analysis-2p

      # - name: Install Apptainer
      # # Note that that doesn't work on a local runner 
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y apptainer

      - name: Build Singularity image
        run: |
          if ! command -v apptainer &> /dev/null; then
            echo "apptainer could not be found"
            echo "Please install apptainer from https://apptainer.org/docs/admin/main/installation.html#install-ubuntu-packages"
            exit 1
          fi
          apptainer build -F analysis-2p_latest.sif docker://wanglabneuro/analysis-2p:latest 

      # - name: Install sshpass
      # # Same note as above
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Singularity image to HPCC
        run: |
          export SSH_HPCC_IMAGE_REPO="${{ secrets.HPCC_SERVER }}:${{ secrets.HPCC_IMAGE_REPO }}"
          if [ -n "${SSH_HPCC_IMAGE_REPO+x}" ]; then
            echo "Copying Singularity image to HPCC."
            rsync -aP --rsh="sshpass -p '${{ secrets.HPCC_PWD }}' ssh -o StrictHostKeyChecking=no" analysis-2p_latest.sif "${{ secrets.HPCC_LOGIN }}@$SSH_HPCC_IMAGE_REPO/"
          else
            echo "HPPC_IMAGE_REPO variable not set. Not copying to HPPC."
          fi
