# Run the mcorr cnmf pipeline on test data on the local runner

# To update the `yml` file without triggering the job, use the `[skip ci]` or `[ci skip]` keyword in your commit message. 
# e.g.:
# ```
# Update run_batch_mcorr_cnmf_pipeline.yml [skip ci]
# ```

name: Test MCorr CNMF Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Create logs directory
        run: |
            mkdir -p Mesmerize/logs
            
      - name: Run batch mcorr cnmf pipeline
        run: |
            # Source conda to enable the commands
            source ~/mambaforge/etc/profile.d/conda.sh
            # Activate the conda environment
            conda activate mescore
            # Resolve the absolute path of the JSON file
            # PATHS_FILE=$(realpath Mesmerize/paths/paths_test_data.json)
            # List the directory to verify the file exists
            ls -l Mesmerize/paths
            # Use GITHUB_WORKSPACE to build the absolute path
            PATHS_FILE=$(realpath "$GITHUB_WORKSPACE/Mesmerize/paths/paths_test_data.json")
            echo "Using JSON file: $PATHS_FILE"
            # Run the pipeline
            python Mesmerize/batch_mcorr_cnmf.py $PATHS_FILE

      - name: Check logs
        run: |
            # Check the logs for errors
            if grep -q "ERROR" Mesmerize/logs/*.log; then
                echo "Errors found in logs"
                exit 1
            else
                echo "No errors found in logs"
            fi

      - name: Check output
        run: |
            # Check the export path (in export_paths field in paths_test_data.json)
            EXPORT_PATH=$(jq -r '.export_paths[0]' Mesmerize/paths/paths_test_data.json)
            # List the files in the export path
            echo "Files in export path:"
            ls -l $EXPORT_PATH
            # Check if the output files exist
            if [ -f "$EXPORT_PATH/results_caiman.mat" ]; then
                echo "Output file results_caiman.mat exists"
            else
                echo "Output file results_caiman.mat does not exist"
                exit 1
            fi

      - name: Deactivate conda environment
        run: |
              conda deactivate

      - name: Delete logs directory
        run: |
              rm -rf Mesmerize/logs              

      - name: Delete output directory
        if: always()
        run: |
              rm -rf $EXPORT_PATH
